# Ansible script to copy ~/.kube/config from remote machine to local

# Target host group, connection settings, and variables
- hosts: kubeMain # Targeting hosts in the kube_agents group
  become: false # Not becoming root for these tasks
  remote_user: ubuntu # Connecting using the ubuntu user

  # Tasks
  tasks:
    # Task: Copy ~/.kube/config from remote machine to local
    - name: Copy ~/.kube/config to local
      fetch:
        src: "~/.kube/config"
        dest: "./" # Copy to the local current working directory
        flat: yes # Flatten the directory structure on the local machine
